Сборка проекта переведена на library-project-plugin
yoomoney-tech/db-queue pull request #11
Opened 2021-04-19 13:45 UTC by GSkoba

2021-04-19 13:51 UTC, f0y requested changes

2021-04-19 13:51 UTC, f0y commented on CHANGELOG.md
> +### NEXT_VERSION_TYPE=MAJOR
Для клиентов это patch

2021-04-19 13:51 UTC, f0y commented on project.gradle
> +        classpath 'ru.yoomoney.gradle.plugins:gradle-project-plugin:7.+'
разве это нужно?

2021-04-19 13:51 UTC, f0y commented on project.gradle
> +    maven { url 'https://oss.sonatype.org/content/repositories/snapshots'}
убрать snapshot

2021-04-19 13:51 UTC, f0y commented on project.gradle
> +    jcenter()
для чего jcenter?

2021-04-20 13:43 UTC, GSkoba commented on project.gradle
> +    maven { url 'https://oss.sonatype.org/content/repositories/snapshots'}
в github так не хватает action task

2021-04-20 13:45 UTC, GSkoba commented on project.gradle
> +    jcenter()
не нужен, убрал

2021-04-20 13:45 UTC, GSkoba commented on project.gradle
> +        classpath 'ru.yoomoney.gradle.plugins:gradle-project-plugin:7.+'
спс, убрал

2021-04-20 13:45 UTC, GSkoba commented on CHANGELOG.md
> +### NEXT_VERSION_TYPE=MAJOR
ты прав, изменил на patch

2021-04-21 08:20 UTC, GSkoba commented on project.gradle
> +    maven { url 'https://oss.sonatype.org/content/repositories/snapshots'}
- [ ] убрать snapshot

2021-04-21 08:28 UTC, f0y commented
- [ ] Надо исправить readme, поскольку мы переехали на maven central. бэйджи вверху + информация по подключению

2021-04-21 08:28 UTC, f0y requested changes

2021-04-21 08:28 UTC, f0y commented on CHANGELOG.md
> +* Сборка проекта переведена на library-project-plugin.
здесь англоязычный проект

2021-04-22 08:05 UTC, f0y requested changes

2021-04-22 08:05 UTC, f0y commented on README.md
> +[![Download](https://api.bintray.com/packages/yoomoney-tech/maven/db-queue/images/download.svg)](https://search.maven.org/artifact/ru.yoomoney.tech/db-queue)
* [ ] Здесь осталась ссылка на иконку bintray

2021-04-22 13:41 UTC, f0y approved these changes

2021-04-22 13:44 UTC, merged